### PR TITLE
added rtx4090 laptop results

### PR DESCRIPTION
**Pull request by alexziskind1**
These are my RTX4090 laptop results. Thanks!

### CODE REVIEW

**Comment by TristanBilot** [comment]
Thanks again Alexander, strange that your RTX4090 is faster than the TESLA V100 on multiple benchs, maybe the examples are still too small?

**Comment by TristanBilot** [comment]
Could you just add how much GB has your RTX4090?

**Comment by alexziskind1** [comment]
yes, will add memory to pr

**Comment by alexziskind1** [comment]
Done!

**Comment by TristanBilot** [comment]
good! thanks

**Pull request merged**
