### PR TITLE
Benchmark for M2

### PR DESCRIPTION
**Pull request by dasayan05**
Here's my run for benchmark on `M2` chip.

### CODE REVIEW

**Comment by dasayan05** [comment]
The convolutions are so bad ! 😢

**Comment by TristanBilot** [comment]
Amazing! Thanks @dasayan05, it's merged

**Comment by TristanBilot** [comment]
yes convolutions are even worst using M2 than M1 Pro! I don't get why it's so bad yet

**Comment by TristanBilot** [comment]
how much RAM do you have?

**Comment by dasayan05** [comment]
> how much RAM do you have?

16GB @TristanBilot

**Pull request merged**
