### PR TITLE
Benchmarks for M2 Ultra and M3 Max added

### PR DESCRIPTION
**Pull request by ivanfioravanti**
Benchmarks added for:
- M2 Ultra (cores: 8E+16P+76GPU)
- M3 Max (cores: 4E+12P+40GPU)

### CODE REVIEW

**Comment by TristanBilot** [comment]
Thanks Ivan! 
I would like your advice on something, I don't know which way to compute the speedup is better, the first one: `v[h] = v["mlx_cpu"] / v["mlx_gpu"] - 1`, or using the same way as in mlx: `(v["mlx_cpu"] - v["mlx_gpu"]) / v["mlx_cpu"]`. The second one has a maximum upper bound of 1, whereas the negative values can go further down. Any suggestions?

**Comment by ivanfioravanti** [comment]
I like the current one in the code. It makes you read it like "0,5X faster or -0,5X slower"
I updated the benchmarks for M2 Ultra and M3 Max with latest operations you added.

**Comment by TristanBilot** [comment]
hi @ivanfioravanti, I did some major upgrades today and I think it's now more stable and prettier (using percentages with respect to mlx in the speedup calculation instead of the raw coefficients with respect to mps and cpu).

Do you mind running the benchmark one last time so that I can merge your PR?
Thx!!

**Comment by ivanfioravanti** [comment]
Tomorrow morning I’ll update eveyrthing

**Pull request closed without merging**
